# Generated by Django 3.0.7 on 2020-10-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0004_auto_20201012_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='number_of_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
